### ISSUE TITLE
from dgcnn_util import pointnet_fp_module

### ISSUE THREAD

**Issue by longmalongma** [FrankCAN/ShufflePointNet#1]
from dgcnn_util import pointnet_fp_module,I do not find the function of pointnet_fp_module in dgcnn_util.

**Comment by FrankCAN** [comment]
Hi, thanks for your remind, I already update the files, now everything works well. Thanks.

**Comment by longmalongma** [comment]
Hi,can you send me your visualization of segmentation on s3dis to my email?such as mangy ply files.

**Comment by FrankCAN** [comment]
Hi, it's quite sample, the code will generate obj files for prediction results and ground truth, then you just need install MashLab to open it. That's it.

**Comment by longmalongma** [comment]
> Hi, it's quite sample, the code will generate obj files for prediction results and ground truth, then you just need install MashLab to open it. That's it.

ok,I will try to run it. but I try to run DGCNN code about semantic segmentaion,I meet this problem,do you know why?

InternalError (see above for traceback): Blas xGEMM launch failed : a.shape=[1,4096,3], b.shape=[1,3,4096], m=4096, n=4096, k=3
[[Node: MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ExpandDims_1, transpose)]]
[[Node: adj_conv2/bn/cond/add_1/_223 = _Recvclient_terminated=false,
