### ISSUE TITLE
Blas xGEMMBatched launch failed : a.shape=[4,1024,3], b.shape=[4,3,4096], m=1024, n=4096, k=3, batch_size=4

### ISSUE THREAD

**Issue by longmalongma** [FrankCAN/ShufflePointNet#3]
hi,when i try to run your code,i meet this problem,can you tell me how to solve this problem?
Blas xGEMMBatched launch failed : a.shape=[4,1024,3], b.shape=[4,3,4096], m=1024, n=4096, k=3, batch_size=4
	 [[Node: tower_0/layer1/MatMul = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_0/GatherPoint, tower_0/layer1/transpose)]]
	 [[Node: tower_0/div/_3077 = _Recv[client_term

**Comment by FrankCAN** [comment]
Hi, can you please give me some detailed computer environment, for example tensorflow version, cuda/cudnn version, python version? Besides, do you use pycharm to run the code?

Honestly speaking, I never met this problem, I am  sure it's definitely you environment problem, maybe I can help you spot the problem.

**Comment by longmalongma** [comment]
> ever met this proble

Thanks for your reply, my environment is ok, because I successfully implement semantic segmentation by pointnet on s3dis dataset.but when i run your code,i meet this problem.
my experimental environment of this algorithm is based on Linux Ubuntu 16.04 operating system. The hardware is Intel i7 8700k Core Six-core CPU and one GeForce RTX 2080 GAMING (8GB memory) GPU. The programming development environment is CUDA-Toolkit 9.0, and Cudnn 7.13 is used as the network GPU acceleration library. The deep learning framework is Tensorflow-gpu, version 1.9.0. the python version is 2.7.
I do not think the problem is my deep leanrning environment,because i can implement other codes except for your codes and dgcnn codes. i suspect my gpu(8g) memory is insufficient, because your codes is run by two gpus, i only have one gpu.

**Comment by FrankCAN** [comment]
Hi, sorry for my late response. you will see "oom when allocating tensor with shape xxx" if your gpu memory is insufficient. You also can try different tensorflow-gpu version, for example 1.6.

Besides, it might be memory problem if the model runs well on ModelNet40 dataset.
