### ISSUE TITLE
how to write color to label on vkitti dataset?

### ISSUE THREAD

**Issue by longmalongma** [FrankCAN/ShufflePointNet#4]
how to write color to label on vkitti dataset?Ｉ do not think you define color of label of vkitti.

**Comment by FrankCAN** [comment]
Hi, sorry for that I didn't visulize results for kitti dataset. Besides, what I use is kitti (sampled to 16384 points), rather than vkitti, which only has 4096 points.

**Comment by longmalongma** [comment]
> Hi, sorry for that I didn't visulize results for kitti dataset. Besides, what I use is kitti (sampled to 16384 points), rather than vkitti, which only has 4096 points.

Thanks
