### ISSUE TITLE
your email

### ISSUE THREAD

**Issue by longmalongma** [FrankCAN/ShufflePointNet#5]
Hello,Can Chen, I have been following and paying attention to every research and paper of yours. Could you please give me your email? I have a question to ask you.looking forwarding to your reply.

**Comment by FrankCAN** [comment]
Hi, very glad you are interested in my papers, my email address is can.chen@cranfield.ac.uk, thanks.

**Comment by longmalongma** [comment]
> Hi, very glad you are interested in my papers, my email address is [can.chen@cranfield.ac.uk](mailto:can.chen@cranfield.ac.uk), thanks.



> Hi, very glad you are interested in my papers, my email address is [can.chen@cranfield.ac.uk](mailto:can.chen@cranfield.ac.uk), thanks.

thank you very much!
